<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eCommerce.Storefront.Services\eCommerce.Storefront.Services.csproj" />
    <ProjectReference Include="..\eCommerce.Storefront.Services.Cache\eCommerce.Storefront.Services.Cache.csproj" />
  </ItemGroup>

</Project>